### ISSUE TITLE
问题：在接口超出限制的情况下，调用直接报错。

### ISSUE THREAD

**Issue by zqj** [lanrion/weixin_authorize#28]
user_info_handler = weixin_client.user(ENV["OPENID"])
            puts user_info_handler.en_msg # 打印出英文提示信息
            puts user_info_handler.cn_msg

Completed 500 Internal Server Error in 198ms

WeixinAuthorize::ValidAccessTokenException (45009: api freq out of limit(接口调用超过限制).):

**Comment by lanrion** [comment]
接口限制类似的错误，在Rails框架下，可以建议使用
```ruby
rescue_from WeixinAuthorize::ValidAccessTokenException， with: :your_handler
```
