### ISSUE TITLE
支持模板消息

### ISSUE THREAD

**Issue by OhCoder** [lanrion/weixin_authorize#37]
请问，现在的提供的API里有发送模板消息的功能吗？

**Comment by lanrion** [comment]
@OhCoder 不支持，目前测试公众号没的这个权限。有需要的话，需要提供测试号给我，提供支持。

**Comment by OhCoder** [comment]
@lanrion 
好的，多谢回复。后面等服务号认证之后，如有需要还请帮忙，:)

**Comment by OhCoder** [comment]
你好。如果現在想讓你幫忙添加支持模板消息的功能，需要我提供哪些信息？

**Comment by lanrion** [comment]
认证后的服务号账号与密码，并且有 App Secret，同时确保模板消息接口已经申请。

**Comment by OhCoder** [comment]
可能给不了账号和密码，现在的公共账号正在运营。
 最多给appid和app secret，以及相应的模板id
这个我觉得应该可以了吧。

**Comment by OhCoder** [comment]
根据文档 http://mp.weixin.qq.com/wiki/17/304c1885ea66dbedf7dc170d84999a9d.html
只要获取access_token和template_id就可以了。
不过这个功能你可能两个gem都要更新，一个是高级的，提供发送功能，另一个是初级的那个，可以接收发送状态。

**Comment by OhCoder** [comment]
算了，别忙活了，刚才公司决定先试着自己做了，有问题再麻烦你吧。:)

**Comment by lanrion** [comment]
@OhCoder 呃，欢迎发PR。

**Comment by lanrion** [comment]
@OhCoder 

晚上对接了模板消息API，比较简单，主要是在测试上，可以麻烦你按照以下的使用wiki，结合你的公众号进行测试一下，如果测试OK，我合并到Master，非常感谢。

# 引用配置
Gemfile
```ruby
gem  "weixin_authorize", git: "https://github.com/lanrion/weixin_authorize.git", branch: "add-template-message-api"
```
# 使用API

```ruby
 #设置所属行业
 client.set_template_industry(industry_id1, industry_id2)

# 获得模板ID
# code: 模板库中模板的编号，有“TM**”和“OPENTMTM**”等形式
client.add_template(code)

# 发送模板消息
# data 需要开发者自己组合相应模板的Hash结构
client.send_template_msg(touser, template_id, url, topcolor, data)
```

详见：https://github.com/lanrion/weixin_authorize/pull/41/files

**Comment by OhCoder** [comment]
cool, :)
稍后我会试下，然后给你留言。

**Comment by OhCoder** [comment]
def set_template_industry(industry_id1, industry_id2) 和
def add_template(code)  
上面两个方法测试了一下，应该没有问题。
def send_template_msg(touser, template_id, url, topcolor, data)
出现503错误。下面截图是调用结果
![client](https://cloud.githubusercontent.com/assets/890676/5934227/31078cba-a707-11e4-81f5-57cabb0e0749.png)
![return](https://cloud.githubusercontent.com/assets/890676/5934228/31820aa8-a707-11e4-8c56-afa7c43d26e4.png)

不清楚是不是发送的URL问题……
https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=ACCESS_TOKEN
你可以看下。

**Comment by OhCoder** [comment]
最终post使用的token和我表里的token不一样。
![screen](https://cloud.githubusercontent.com/assets/890676/5935024/881dfcbe-a711-11e4-81c7-91aa300f88f4.png)

**Comment by lanrion** [comment]
代码已经更新，请重新bundle install 更新，同时最好涉及到的所有API，也重新测试一下。

**Comment by OhCoder** [comment]
感谢更新！
先试了一下前两个方法：
调用client.set_template_industry(industry_id1, industry_id2)方法，发现access_token和我自己存储的那个貌似不一样，貌似是在调用client.set_template_industry(industry_id1, industry_id2)方法的时候又去取了一次access_token。
![screen shot 2015-01-28 at 22 20 21](https://cloud.githubusercontent.com/assets/890676/5939154/53681970-a73c-11e4-8928-d108524ad047.png)

调用client.add_template(code)方法，调用结果如下：
![screen shot 2015-01-28 at 22 18 44](https://cloud.githubusercontent.com/assets/890676/5939165/6550d3b6-a73c-11e4-8052-c4584e396e9a.png)
貌似也是access_token的问题。
说明一下，account.get_access_token方法是我自己封装的一个方法，目的是希望token过期的时候才去取，而不是每次调用都去频繁的去取token，每次取完之后放到数据库的表里。

**Comment by lanrion** [comment]
代码再次更新，修复 "set_template_industry" API 404的问题。
 weixin_authorize 已经有自己的方案存储access_token了，见：https://github.com/lanrion/weixin_authorize/wiki/Getting-Started#%E5%A4%9A%E4%B8%AA%E5%85%AC%E4%BC%97%E8%B4%A6%E5%8F%B7%E6%83%85%E5%86%B5%E4%B8%8B%E5%BC%BA%E7%83%88%E5%BB%BA%E8%AE%AE%E4%BD%BF%E7%94%A8-redis%E6%9D%A5%E4%BF%9D%E5%AD%98access_token 

如果你自己再去手动处理token，我也没办法控制token的一致性，也并非是此gem的问题了。

**Comment by lanrion** [comment]
请熟读 https://github.com/lanrion/weixin_authorize/wiki/Getting-Started 此wiki，充分了解了此gem的特性。

**Comment by OhCoder** [comment]
你这篇wiki里貌似没有提到get_access_token 这个方法，但我刚才发现client实例上可以调用get_access_token方法，你的这个方法会根据失效时间进行判断吗？

**Comment by OhCoder** [comment]
呃，我看到了，你用redis做缓存

**Comment by lanrion** [comment]
不提及 get_access_token 方法，是不建议让你们直接调用token，token的管理的目标是面向开发者是透明的，你们无需关心。

如果你是用 对象缓存的话，你在之前用 get_access_token 获取的token存到数据库中，然后**重启服务器**时再去使用你的数据库的token，我不敢保证，你数据库的token值是否有效。不过，存储方案做成一个可自定义化，是将来的一个提升的特性，我会跟进开发。

目前的情况，建议你使用我的存储方案，进行测试。

**Comment by OhCoder** [comment]
明白，理解你的意思了。
但是现在我们的项目里遇到了这个问题，最近微信新推出的js前端接口，需要设置access_token数值，所以get_access_token方法是有必要让开发者直接调用的。
最早我们也没有写get_access_token方法，直到最近微信推出js接口之后才遇到这个问题。

**Comment by lanrion** [comment]
后期会提供token自定义存储的方案，类似于：https://github.com/lanrion/weixin_rails_middleware/wiki/Custom-Adapter

**Comment by lanrion** [comment]
你是为了使用 js sdk的接口嘛，细心去找一下，我已经实现了：https://github.com/lanrion/weixin_authorize/pull/39 ，并且在项目中使用。
你可以使用这个分支：get-jsticket-for-weixin-jssdk

**Comment by OhCoder** [comment]
呃，我们自己已经实现了……
也好，可以做个参考……

**Comment by OhCoder** [comment]
这次send_template_msg方法调用成功了。如下图：
![screen shot 2015-01-28 at 22 18 44](https://cloud.githubusercontent.com/assets/890676/5941015/5bdb7e78-a749-11e4-843f-d96163c418f9.png)

第一个设置行业的方法返回的状态是“设置过于频繁”，想必应该是成功了，第二个方法也能成功设置模板了。
但是还是有一个疑问，现在调用send_template_msg方法的时候还是会调用access_token，而且一旦token过期调用就会失败，请问有没有方法如何判断当前token是否过期？

**Comment by OhCoder** [comment]
另外，还有一个问题。是关于另一个gem的。
send_template_msg发送成功之后，微信会做回调，返回发送状态，应该是https://github.com/lanrion/weixin_rails_middleware 的功能，官方文档中http://mp.weixin.qq.com/wiki/17/304c1885ea66dbedf7dc170d84999a9d.html 最下面会有事件推送，希望能更新一下另一个gem，让其能够返回发送模板的状态。

**Comment by lanrion** [comment]
关于token的问题，不再讨论，因为你目前是使用自己的存储的方式在管理token，这种方式，此gem并没有明确说明支持。
token过期，已经记录了一个bug, https://github.com/lanrion/weixin_authorize/issues/38 ，后期会进行修正. 
weixin_rails_middleware 只是事件的处理，你可以根据那个事件的类型，再自己加一个方法，去处理即可。

BTW:
如果你想提问题时，请先阅读相关的wiki、issue、PR等信息，看gem是否已经有记录，避免重复解释。
