### ISSUE TITLE
restclient Request Timeout

### ISSUE THREAD

**Issue by hanluner** [lanrion/weixin_authorize#43]
自从昨晚凌晨起，restclient Request Timeout的报错信息不停。是不是你那里做了什么改动？

**Comment by lanrion** [comment]
你的 分支、使用版本，异常信息，是哪个接口报错的呢？可否罗列一下？

**Comment by lanrion** [comment]
重新跑了API测试，没有出现 restclient Request Timeout 的问题。

**Comment by hanluner** [comment]
昨天是微信抽风，然后rest-client默认的超时时间不够用。后来微信好了，就没有再报错了。
