### ISSUE TITLE
图文消息没有content选项？

### ISSUE THREAD

**Issue by iamacourser** [lanrion/weixin_authorize#45]
在官文页面里有个content项，我看在这里只有链接到外面页面的。我们能不能实现gem直接群发图文消息，像在微信公众号后台那种的，内容显示在它的服务器（mp.weixin.qq.com)的那种？
我在微信提供的debug页面里发出去的，只能显示title，图片，和内容页都跳不过去。
```
{
    "touser": "owwwHUst1nmXeQp7qh_Ajo6TMvjWI",
    "msgtype": "news",
    "news": {
        "articles": [
            {
                "thumb_media_id": "OMU7YKWr5ZcLyuowwCRPaWkHcQJNKM38i_fFHSLDcCYQOh99bwg_pMzGXHAQutVN",
                "author": "xxx",
                "description": "Is Really A Happy Day",
                "title": "Happy Day",
                "content_source_url": "www.qq.com",
                "content": "content",
                "digest": "digest",
                "show_cover_pic": "1"
            }
        ]
    }
}
```

[http://mp.weixin.qq.com/wiki/15/5380a4e6f02f2ffdc7981a8ed7a40753.html](http://mp.weixin.qq.com/wiki/15/5380a4e6f02f2ffdc7981a8ed7a40753.html)。

**Comment by lanrion** [comment]
你这个属于高级群发接口API。请阅读这个：
https://github.com/lanrion/weixin_authorize/blob/master/spec%2Fapi%2Fmass_spec.rb#L37

**Comment by iamacourser** [comment]
@lanrion 谢谢，这也是我rspec跑测试不过的地方，应该是要申请了微信认证才有的接口。
