### ISSUE TITLE
自定义菜单提交时，如view类型url字段包含&则无法成功提交

### ISSUE THREAD

**Issue by akirapanda** [lanrion/weixin_authorize#46]
Hi,
  我在最近的使用中发现一个问题，如view类型的url字段包含&,则在Json.load后转移成了\u0026形式的unicode，可能会导致成功的提交 menu create的请求。
  本人的环境是rails 4.0，编码为UTF8。不知道是不是一个偶发性的问题。

**Comment by lanrion** [comment]
偶发性的问题吧，目前项目中，都没遇到过你的问题。
如果需要及时反馈，有问题，请直接 http://weixin-dev.com/topics 这里发贴。
