### ISSUE TITLE
authorize_url没返回code

### ISSUE THREAD

**Issue by nancy-luo** [lanrion/weixin_authorize#48]
client.authorize_url("jd.cn")
返回信息
=> "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx61e6a632b58abasd1&redirect_uri=jd.cn&response_type=code&scope=snsapi_base&state=weixin#wechat_redirect"

微信服务器怎么没将CODE回传呢？

**Comment by lanrion** [comment]
有问题，请前往：http://weixin-dev.com/topics 提问。

引用官方文档: 
>1、在微信公众号请求用户网页授权之前，开发者需要先到公众平台官网中的开发者中心页配置授权回调域名。请注意，这里填写的是域名（是一个字符串），而不是URL，因此请勿加http://等协议头；
2、授权回调域名配置规范为全域名，比如需要网页授权的域名为：www.qq.com，配置以后此域名下面的页面http://www.qq.com/music.html 、 http://www.qq.com/login.html 都可以进行OAuth2.0鉴权。但http://pay.qq.com 、 http://music.qq.com 、 http://qq.com无法进行OAuth2.0鉴权
3、如果公众号登录授权给了第三方开发者来进行管理，则不必做任何设置，由第三方代替公众号实现网页授权即可

如还未解决，请前往：http://weixin-dev.com/topics 发贴。及时为你解答。
