### ISSUE TITLE
下载下来了的图片可以用carrierwave处理？

### ISSUE THREAD

**Issue by gaoguoxin** [lanrion/weixin_authorize#49]
我直接利用wget下在了jssdk上传的图片，然后carrierwave做了处理，貌似render到页面的时候访问不到啊

**Comment by lanrion** [comment]
有问题，可以前往：http://weixin-dev.com/ 提问

你应该直接使用 carrierwave 去下载图片。
如果你使用了我的 weixin_rails_middleware gem，则：
```ruby
 def response_image_message(options={})
    pic_url = @weixin_message.PicUrl
    wx_pic = WxPic.new
    wx_pic.remote_pic_url = pic_url  # pic_url 为一个字段且： mount_uploader :picture, PicUploader
   wx_pic.save
end
````
即可。

另外值得注意的是，最好使用队列来下载图片。

有问题，可以前往：http://weixin-dev.com/ 提问。

**Comment by gaoguoxin** [comment]
@lanrion 已经顺利完成了所需的工作，就是利用了carrierwave的remote_url来实现的，下载图片利用了sidekiq，谢谢。
