### ISSUE TITLE
生成字符串参数永久二维码问题

### ISSUE THREAD

**Issue by zouh** [lanrion/weixin_authorize#51]
生成字符串参数的永久二维码，参数如果传入options[:scene_str]， 则action_name不应是QR_LIMIT_SCENE，而是qrcode_infos = {action_name: "QR_LIMIT_STR_SCENE"}，现在好像没这个分支，如果传字符串，扫描时不能返回

**Comment by lanrion** [comment]
谢谢反馈. 
scene_str、QR_LIMIT_STR_SCENE 不知道是不是当初忽略了还是或者是后期新增的属性，会尽快添加这个属性配置。同时也欢迎发PR来修复。

**Comment by lanrion** [comment]
http://mp.weixin.qq.com/wiki/18/28fc21e7ed87bec960651f0ce873ef8a.html

**Comment by zouh** [comment]
新手，还不太会做修正：）感谢你的开源项目让微信开发方便很多！
