### ISSUE TITLE
由于对应新接口，如何通过 client 获取 access_token 呢，wiki 中提供的http_post貌似不管用，，

### ISSUE THREAD

**Issue by Msms-NJ** [lanrion/weixin_authorize#54]
2.2.0 :003 > client.http_post
NoMethodError: private method `http_post' called for #<WeixinAuthorize::Client:0x007f85d4f17230>

**Comment by lanrion** [comment]
抱歉，wiki上的文档是针对master上的，你更新master分支代码即可，晚点会发布最新的版本。
