### ISSUE TITLE
微信支付

### ISSUE THREAD

**Issue by Wangjiaji007** [lanrion/weixin_authorize#56]
我按照配置做了之后，统一下单时成功的，但是在jsapi 调用的时候
支付宝错 说 `package中的参数partner或prepay_id为空`

但是我检查 prepay_id 是有的，
还有个问题，那个 wx_pay.key 到底是什么？我配的是api 秘钥

**Comment by Wangjiaji007** [comment]
找到问题了，谢谢

**Comment by lanrion** [comment]
欢迎star～
