### ISSUE TITLE
微信卡券接口参数 Map

### ISSUE THREAD

**Issue by u0x01** [lanrion/weixin_authorize#63]
微信卡券由于参数过多，构建Json时，需要传入很多参数。
而官方提供的接口参数文档结构层次不明晰，因此特别整理了一个 API Map 方便各位做开发
微信卡券API基本结构为([详见](https://github.com/u0x010/weixin_doc/blob/master/card/API-Map.pdf))：
- card_type
- (团购券) deal_detail
- (代金券) least_cost
- (代金券) reduce_cost
- (折扣券) discount
- (礼品券) gift
- (优惠券) default_detail
- (会员卡) activate_url
- (会员卡) prerogative
- (会员卡) supply_bonus
- (会员卡) bonus_url
- (会员卡) bonus_cleared
- (会员卡) bonus_rules
- (会员卡) supply_balance
- (会员卡) balance_url
- (会员卡) balance_rules
- (会员卡) custom_field1
- (会员卡) custom_field2
- (会员卡) custom_field3
- (会员卡) custom_cell1
- base_info
  - logo_url
  - code_type
  - brand_name
  - title
  - sub_title
  - color
  - notice
  - description
  - sku
  - date_info
  - use_custom_code
  - bind_openid
  - service_phone
  - location_id_list
  - source
  - custom_url_name
  - custom_url
  - custom_url_sub_title
  - promotion_url_name
  - promotion_url
  - promotion_url_sub_title
  - get_limit
  - can_share
  - can_give_friend

**Comment by lanrion** [comment]
:+1:  欢迎发一个PR。

**Comment by lanrion** [comment]
@u0x010 
微信卡券内测时做得对接测试，接口与json参数可能已过时，仅供参考。
https://github.com/lanrion/weixin_card_package
