### ISSUE TITLE
redis没有存access_token

### ISSUE THREAD

**Issue by mualucky** [lanrion/weixin_authorize#67]
Q1. 没有存储到redis，不知道什么原因
完全按照指导，添加了文件
![screen shot 2015-08-18 at 7 02 07 pm](https://cloud.githubusercontent.com/assets/9458206/9328487/b3edf312-45db-11e5-867a-c31b36203962.png)

redis里没用任何key
![screen shot 2015-08-18 at 7 02 46 pm](https://cloud.githubusercontent.com/assets/9458206/9328672/44c989d6-45dd-11e5-8383-0e08849acc27.png)

Q2. gem没有说$client在何处初始化，我把$client的初始化放入了weixin_authorize.rb中，是否合适？如果这是一个合适的办法，为什么不默认生成这个文件并初始化client？

Q3. 启动rails server后,直接调用client.access_token返回nil，必须调用is_valid?后，再调用access_token才返回有值，为什么？
![screen shot 2015-08-18 at 7 17 37 pm](https://cloud.githubusercontent.com/assets/9458206/9328744/098c8d2c-45de-11e5-90d4-412e065e5a76.png)

**Comment by lanrion** [comment]
Q1的问题：当你执行完Q3的命令后，便会产生这个KEY。
Q2的问题：如果你只是一个公众号，我的建议是全局变量放在项目的config/initializers目录下，如果是多个公众号的情况，则直接在你需要的调用微信接口的时候重新new一个。
Q3的问题：调用`is_valid `当时的想法是为了确保你的配置是对的，但后来发现这种设计并不可取，2.0后的版本会变成自动重试刷新（见 https://github.com/lanrion/weixin_authorize/issues/38 ）。

**Comment by u0x010** [comment]
$client 初始化操作请放到 config/application.rb 中

另外，你的代码拓扑是有错误的。既然是用了多公众号方案，就不应该使用全局$client

而是在调用高级参数前实例化 对象 
```ruby
@client = new....
```
