### ISSUE TITLE
这个gem能提供一个参考的demo么？

### ISSUE THREAD

**Issue by xprimes** [lanrion/weixin_authorize#75]
感谢lanrion的gem，不过使用上感觉还是有些门槛，不知道有没有提供一个demo参考下呢

**Comment by lanrion** [comment]
没有具体的demo。

看这个：
https://github.com/lanrion/weixin_authorize/wiki/Getting-Started

看看测试用例，https://github.com/lanrion/weixin_authorize/tree/master/spec
