### ISSUE TITLE
出现40001错误怎么用redis 储存access_token

### ISSUE THREAD

**Issue by liguangsong** [lanrion/weixin_authorize#76]

**Comment by liguangsong** [comment]
$client ||= WeixinAuthorize::Client.new( APP_ID, APP_SECRET)?要放到config/initializers么我放到controller里了为什么会有4001错误

**Comment by liguangsong** [comment]
一定要用redis么，是不是不用redis也不影响，不用任何配置

**Comment by lanrion** [comment]
可以使用 $client.is_valid? 来检测你的token是否有效。

**Comment by liguangsong** [comment]
@lanrion  如果失效了怎么办，再执行一次$client ||= WeixinAuthorize::Client.new( APP_ID, APP_SECRET)?

**Comment by lanrion** [comment]
@liguangsong 这个问题是一个bug，我还没有修复，为了防止出现token失效引起40001的情况，现在可以使用 `$client.is_valid?`来再次获取token。

**Comment by lanrion** [comment]
@liguangsong 这个也是你提的呀。

**Comment by lanrion** [comment]
@liguangsong 你们使用的是什么web server？不知道是不是多线程引起的bug。

**Comment by lanrion** [comment]
升级到 1.6.4，可以解决此问题。
