### ISSUE TITLE
refresh_token 时应当加锁

### ISSUE THREAD

**Issue by MikeChou** [lanrion/weixin_authorize#81]
当 token 失效时 get_access_token 会 refresh_token
如果不加锁，可能会发生 race condition：
两个进程在很短时间内先后 refresh_token，如果后生成的 token 先返回，先生成的 token 后返回，在 redis 中，后者（无效）把前者（有效）覆盖，导致之后调用因 token 无效而失败
我不止一次出现这样的情况

**Comment by lanrion** [comment]
难道之前一直出现无效token的问题，就是这个原因？

**Comment by lanrion** [comment]
估计要加个同步锁。
你是用了puma?

**Comment by MikeChou** [comment]
我自己在使用的过程中遇到的问题都是下载图片时返回（吐槽一下居然是200！）：
```json
{
  "errcode" : 40001,
  "errmsg" :  "invalid credential, access_token is invalid or not latest hint: [Feqffa0754ent1]"
}
```
其中hint是每次不同的

我用的不是 puma，我觉得与这个没有关系。只要是有多出能够同时独立访问redis的（比如多个process，多台机器）都会有这个问题。

**Comment by lanrion** [comment]
应该是并发导致，你们自行修复了吗？如果可以的话，发个MR帮忙修复？

**Comment by lanrion** [comment]
这个跟秒杀超库存是一样的问题。

**Comment by lanrion** [comment]
升级到 1.6.4，应该可以解决此问题。

**Comment by MikeChou** [comment]
我看了一下，似乎你的解决方案只能解决同一进程中的不同线程之间的冲突，然而通常比较大规模的应用可能使用了多个进程，甚至这些进程分布于不同的主机上。所以比较正确的解决方案是利用 redis 本身来加锁。
如果你没有空解决，我过一段时间可能会写一个。

**Comment by lanrion** [comment]
@MikeChou 你指的是setnx来加锁吧，加了锁还得解锁，不建议使用redis加锁，会平增一个依赖，而且性能并不高。如果要处理掉，要实现一个CAS无锁编程。Redis貌似并未实现CAS（redis redlock），memcached都实现了。

有空可以搞一个CAS Ruby版就赞了。

**Comment by lanrion** [comment]
目前通过增大提前刷新token的时间后，可得到不错的解决。
