### ISSUE TITLE
在微信授权中无法跳转到制定的redirect_url中,其中redirect_url中包含多个参数

### ISSUE THREAD

**Issue by lzm420241** [lanrion/weixin_authorize#86]
例如:
`
@client = WeixinAuthorize::Client.new(app_config["app_id"], app_config["app_secret"]) 
if code.nil? 
     @client.authorize_url(request.url) 
end
`
通过上面的方式当授权的时候无法跳入指定的request.url

**Comment by lanrion** [comment]
如果是rails，authorize_url只是帮你生成授权URL，你要自己redirect_to 。
相关文档：https://github.com/lanrion/weixin_authorize/wiki/get-openid#application_controllerrb
