### ISSUE TITLE
如何获取微信全部素材列表

### ISSUE THREAD

**Issue by yanchengv** [lanrion/weixin_authorize#90]
请问有获取微信素材列表的接口吗？

微信api接口调用请求说明
https://mp.weixin.qq.com/wiki/12/2108cd7aafff7f388f41f37efa710204.html

http请求方式: POST
https://api.weixin.qq.com/cgi-bin/material/batchget_material?access_token=ACCESS_TOKEN
调用示例

{
    "type":TYPE,
    "offset":OFFSET,
    "count":COUNT
}

**Comment by lanrion** [comment]
是这个：https://github.com/lanrion/weixin_authorize/blob/master/lib%2Fweixin_authorize%2Fapi%2Fmedia.rb

**Comment by yanchengv** [comment]
@lanrion 有获取所有素材列表的接口吗？，目前看到的api都是根据media_id来获取素材的

**Comment by yanchengv** [comment]
使用自定义接口获取：
$weixin.http_post('/material/batchget_material', {type:'image', offset:0, count:10}

**Comment by lanrion** [comment]
@yanchengv 👍 👍
