### ISSUE TITLE
创建自定义菜单失败

### ISSUE THREAD

**Issue by dannyxu2015** [lanrion/weixin_authorize#92]
I've tried to create customize menu by following command in rails console:
```
  wx_client = WeixinAuthorize::Client.new my_mp_appid my_mp_appsecret
  menu = {...}
  wx_client.create_menu menu
```
But I got following error:
```
RestClient::SSLCertificateNotVerified: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed: 
	。。。（backtrace information)
```
 以前我创建过多次都没问题的，今天就出现这样的状况，我将gem升级到最新版（v1.6.4）之后重新运行，结果还是一样。。。
检查过appid 和 appsecret，是正确的

**Comment by lanrion** [comment]
现在gem默认要使用SSL，你要检查一下自己的环境的openssl安装得正不正确。
如果不想使用SSL，则查看对应的文档：https://github.com/lanrion/weixin_authorize/wiki/config#restclient-%E6%89%A9%E5%B1%95%E9%85%8D%E7%BD%AE

**Comment by dannyxu2015** [comment]
嗯，是ssl配置问题，mac os x升级后出现的，参考https://github.com/rest-client/rest-client/issues/288和https://toadle.me/2015/04/16/fixing-failing-ssl-verification-with-rvm.html后已解决了：）
