### ISSUE TITLE
调用分享到朋友圈接口，没反应也没有报错

### ISSUE THREAD

**Issue by goody9807** [lanrion/weixin_authorize#93]
key 和 secret 都已经校验正确
onMenuShareTimeline接口也有权限访问

`    wx.ready(function () {
 
        wx.onMenuShareTimeline({
            title: "测试分享",
            link: "http://www.xxx.com",
            imgUrl: "http://www.xxx.com/assets/u1-069a31b97f8f4375449b676ef3f0249b1b1a4443eebb1bdd7af4a23d71f0c4af.jpg",
            success: function () {
                alert('success');
            },
            cancel: function () {
                alert('cancel');
            },
            fail: function () {
                alert('fail');
            }
        });

       
        wx.error(function (res) {
            alert(res);
        });

    });`

这样调用没有反应

**Comment by lanrion** [comment]
使用 微信web开发者工具 查看一下是什么错误，应该是js错误。

**Comment by goody9807** [comment]
我知道了，谢谢，这个接口不是主动调用的，而是获取点击分享朋友圈状态的接口

**Comment by skyFi** [comment]
你好，那有主动调用分享朋友圈的接口吗？谢谢了
