### ISSUE TITLE
redis没有保存上access_token

### ISSUE THREAD

**Issue by yanchengv** [lanrion/weixin_authorize#97]
按文档设置了`weixin_authorize.rb`文件，然后`$weixin.is_valid?`，$weixin.access_token有值了，但是redis中没有保存相应的值

**Comment by lanrion** [comment]
`$weixin.is_valid? ` 返回是true还是false?

**Comment by lanrion** [comment]
Redis 有没有保存相应的值？首先得确保你使用了Redis ： https://github.com/lanrion/weixin_authorize/wiki/config
执行 `$weixin. get_access_token` 看有没有值。

**Comment by yanchengv** [comment]
1. 以上问题解决了。配置没有问题。
只有执行`$weixin. get_access_token`才会保存到redis,之前一直命令行执行`$weixin.access_token`是保存不到redis的。
2. 另外redis存储单个服务号，$weixin = new...放在initializers/costants.rb文件下没问题吧，对于存放位置有要求吗？

谢谢

**Comment by lanrion** [comment]
可以放在initializers/costants.rb文件下。
